services:
    Google\Client:
        class: Google\Client
        calls:
            # Authentication with "OAuth 2.0" or "Service account" using JSON
            - [setAuthConfig, ['%kernel.project_dir%/google_auth_config.json']]
